/// http method enum

#define TC_HTTP_OPTION_CODE_GET(X) 						((X)+1)
#define TC_HTTP_OPTION_CODE_SET(X) 						(0xff00|((X)+1))
#define TC_HTTP_OPTION_CODE__IS_SET(X) 					(0xff00&(X))

typedef enum __tc_http_method {
	TC_HTTP_METHOD_GET       								=  0,
	TC_HTTP_METHOD_POST    									=  1,
	TC_HTTP_METHOD_HEAD      								=  2,
	TC_HTTP_METHOD_PUT       								=  3,
	TC_HTTP_METHOD_OPTIONS   								=  4,
	TC_HTTP_METHOD_DELETE    								=  5,
	TC_HTTP_METHOD_TRACE     								=  6,
	TC_HTTP_METHOD_CONNECT   								=  7,
} tc_http_method_e;

typedef enum __tc_http_code_e  {
	TTC_HTTP_CODE_CONTINUE 									= 100,
	TC_HTTP_CODE_SWITCHING_PROTOCOLS 						= 101,
	TC_HTTP_CODE_PROCESSING			 						= 102,

	TC_HTTP_CODE_OK						    				= 200,
	TC_HTTP_CODE_CREATED									= 201,
	TC_HTTP_CODE_ACCEPTED 									= 202,
	TC_HTTP_CODE_NON_AUTHORITATIVE_INFORMATION 				= 203,
	TC_HTTP_CODE_NO_CONTENT 								= 204,
	TC_HTTP_CODE_RESET_CONTENT								= 205,
	TC_HTTP_CODE_PARTIAL_CONTENT   							= 206,

	TC_HTTP_CODE_MULTIPLE_CHOICES 							= 300,
	TC_HTTP_CODE_MOVE_PERMANENTLY							= 301,
	TC_HTTP_CODE_MOVE_TEMPORARILY					 		= 302,
	TC_HTTP_CODE_SEE_OTHER							 		= 303,
	TC_HTTP_CODE_NOT_MODIFIED	 							= 304,
	TC_HTTP_CODE_USE_PROXY							 		= 305,
	TC_HTTP_CODE_SWITCH_PROXY						 		= 306,
	TC_HTTP_CODE_TEMPORARY_REDIRECT					 		= 307,

	TC_HTTP_CODE_BAD_REQUEST								= 400,
	TC_HTTP_CODE_UNAUTHORIZED								= 401,
	TC_HTTP_CODE_FORBIDDEN									= 403,
	TC_HTTP_CODE_NOT_FOUND									= 404,
	TC_HTTP_CODE_METHOD_NOT_ALLOW							= 405,
	TC_HTTP_CODE_NOT_ACCEPTABLE 							= 406,
	TC_HTTP_CODE_REQUEST_TIMEOUT							= 408,
	TC_HTTP_CODE_CONFLITC									= 409,
	TC_HTTP_CODE_GONE										= 410,
	TC_HTTP_CODE_LENGTH_REQUIRED							= 411,
	TC_HTTP_CODE_PRECONDITION_FAILED						= 412,
	TC_HTTP_CODE_REQUEST_ENTITY_TOO_LENGTH					= 413,
	TC_HTTP_CODE_REQUSET_URI_ROO_LONG						= 414,
	TC_HTTP_CODE_UNSUPPORTED_MEDIA_TYPE						= 415,
	TC_HTTP_CODE_RANGE_NOT_SATISFIABLE						= 416,
	TC_HTTP_CODE_EXPECTATION_FAIELD							= 417,
	TC_HTTP_CODE_UNPROCESSABLE_ENTITY						= 422,
	TC_HTTP_CODE_LOCKED										= 423,
	TC_HTTP_CODE_FAILD_DEPENDENCY							= 424,
	TC_HTTP_CODE_UNORDERED_COLLECTION						= 425,
	TC_HTTP_CODE_UPGRADE_REQURED							= 426,
	TC_HTTP_CODE_RETRY_WITH									= 429,

	TC_HTTP_CODE_INTERNAL_SERVER_ERROR						= 500,
	TC_HTTP_CODE_NOT_IMPLEMENTED							= 501,
	TC_HTTP_CODE_BAD_GETWAY									= 502,
	TC_HTTP_CODE_SERVICE_UNAVAILABLE						= 503,
	TC_HTTP_CODE_GATEWAY_TIMEOUT							= 504,
	TC_HTTP_CODE_INSUFFICIENT_STORAGE						= 507,
	TC_HTTP_CODE_LOOP_DETECTED								= 508,
	TC_HTTP_CODE_EXTENDED									= 510,
} tc_http_ceode_e;

typedef enum _tc_http_option_e  {
	TC_HTTP_OPTION_NONE										= 0,	
	TC_HTTP_OPTION_GET_SSL									= 0,	
	TC_HTTP_OPTION_GET_URL									= 0,	

} tc_http_option_e;
